---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(sqldf)
library(reticulate)
library(jsonlite)
library(gganimate)
source("test.R")
```

```{r}


ui <- fluidPage(
            fluidRow(column(3,
              sliderInput('testID', h3('Number of Simulations'), 1, 500, 10 , step = 5,), 
              numericInput("num", label = h3("Starting Amount"), value = 100)
            ), 
            fluidRow(column(3, 
               sliderInput('rounds', h3('Number of Rounds'), 1, 50, 10 , step = 2),
               numericInput("std_value", label = h3("Standard Deviation"), value = .2)  
                            ))
  ),
                
            fluidRow(column(4, plotOutput('testoutid')), column(4, plotOutput("test")))
  )  



server <- function(input, output){
  
  

  output$testoutid<-renderCachedPlot(
    
      {
        my_sim <- run_sim(n_sim=500, starting_amount =input$num, row_number=50, std=input$std_value)
        show_plot(my_sim, n_sim=input$testID, row_number = input$rounds, starting_amount = input$num)

        
      },
      cacheKeyExpr = c({input$testID}, {input$num}, {input$rounds}, {input$std_value})
    )
  output$test <- renderCachedPlot(
    
    {
      my_sim <- run_sim(n_sim=500, starting_amount =input$num, row_number=50, std=input$std_value)
      show_plot_new(my_sim, n_sim=input$testID, row_number = input$rounds, starting_amount = input$num)
    }, 
    cacheKeyExpr = c({input$testID}, {input$num}, {input$rounds}, {input$std_value})
    
  )
  
  
    # output$test <- renderImage(
    #   {
    #     my_sim <- run_sim(n_sim=500, starting_amount =input$num, row_number=50, std=input$std_value)
    #     result <- show_plot_new(my_sim, n_sim=input$testID, row_number = input$rounds, starting_amount = input$num)
    #     outfile <- tempfile(fileext='.gif')
    #     anim_save("outfile.gif", animate(result))
    #     list(src = "outfile.gif",contentType = 'image/gif',width = 400,height = 300,alt = "This is alternate text")
    #     
    #     
    #     
    #     
    # 
    #   },
    #   deleteFile = TRUE,
    #   cacheKeyExpr = c({input$testID}, {input$num}, {input$rounds}, {input$std_value})
    # )
    # 
  
  #renderCachedPlot(){
    
  #}
  #assumble input to output
  #output$testoutid dollar sign used to retrieve the testoutid from the output list  
  #output$testoutid <- renderPlot(expr = {hist(rnorm(input$testID))})
  
}
shinyApp(ui=ui, server=server)

```

